### ISSUE TITLE
按照README里的方法替换后无法启动网易云音乐

### ISSUE THREAD

**Issue by chao** [typcn/163music-mac-client-unlock#1]
运行环境：OS X 10.11.4
网易云音乐版本：1.4.2 (444)

错误信息如下：
$ ./NeteaseMusic
2016-03-25 09:01:21.398 NeteaseMusic.org[6022:3252680] NSWindow warning: adding an unknown subview: <INMovableByBackgroundContainerView: 0x7fc3a074ee60>. Break on NSLog to debug.
2016-03-25 09:01:21.399 NeteaseMusic.org[6022:3252680] Call stack:
(
    0   AppKit                              0x00007fff86bd48bb -[NSThemeFrame addSubview:] + 107
    1   AppKit                              0x00007fff86bd4600 -[NSView addSubview:positioned:relativeTo:] + 211
    2   NeteaseMusic.org                    0x0000000102abe5be NeteaseMusic.org + 140734
    3   NeteaseMusic.org                    0x0000000102abd436 NeteaseMusic.org + 136246
    4   NeteaseMusic.org                    0x0000000102abb69d NeteaseMusic.org + 128669
    5   NeteaseMusic.org                    0x0000000102ac6617 NeteaseMusic.org + 173591
    6   AppKit                              0x00007fff86c42e38 -[NSWindowTemplate nibInstantiate] + 559
    7   AppKit                              0x00007fff86b865af -[NSIBObjectData instantiateObject:] + 309
    8   AppKit                              0x00007fff86b85c33 -[NSIBObjectData nibInstantiateWithOwner:options:topLevelObjects:] + 428
    9   AppKit                              0x00007fff86b7ce91 loadNib + 384
    10  AppKit                              0x00007fff86b7c3b7 +[NSBundle(NSNibLoading) _loadNibFile:nameTable:options:withZone:ownerBundle:] + 300
    11  AppKit                              0x00007fff86b7c180 -[NSBundle(NSNibLoading) loadNibNamed:owner:topLevelObjects:] + 201
    12  AppKit                              0x00007fff86b7bf4c +[NSBundle(NSNibLoading) loadNibNamed:owner:] + 344
    13  AppKit                              0x00007fff86b771a6 NSApplicationMain + 466
    14  libdyld.dylib                       0x00007fff8c6aa5ad start + 1
)
dyld: lazy symbol binding failed: Symbol not found: _gliCreateContextWithShared
  Referenced from: /System/Library/Frameworks/OpenGL.framework/Resources/GLEngine.bundle/GLEngine
  Expected in: flat namespace

dyld: Symbol not found: _gliCreateContextWithShared
  Referenced from: /System/Library/Frameworks/OpenGL.framework/Resources/GLEngine.bundle/GLEngine
  Expected in: flat namespace

Trace/BPT trap: 5

**Comment by typcn** [comment]
WTF ..为何会调用 glengine

去掉这一行 https://github.com/typcn/163music-mac-client-unlock/blob/master/NeteaseMusic#L2 

试试？

**Comment by typcn** [comment]
em.. 不 flat namespace 的话注入不成功啊

**Comment by chao** [comment]
去掉DYLD_FORCE_FLAT_NAMESPACE=1倒是可以启动。

**Comment by typcn** [comment]
已修复，请下载最新代码。

**Comment by chao** [comment]
确实可以了。谢谢！
