### ISSUE TITLE
10.11.5 crash

### ISSUE THREAD

**Issue by ahxxm** [typcn/163music-mac-client-unlock#11]
云音乐版本是1.4.2

刚更新系统，用repo里的dylib和自己编译都会崩， crash log http://pastebin.com/P2xNMVuB

**Comment by typcn** [comment]
Dyld Error Message:
  Symbol not found: _gliCreateContextWithShared
  Referenced from: /System/Library/Frameworks/OpenGL.framework/Resources/GLEngine.bundle/GLEngine

GLEngine 。。。 估计是他新链接了库，竟然还上 opengl 了
