### ISSUE TITLE
求更新

### ISSUE THREAD

**Issue by magic-akari** [typcn/163music-mac-client-unlock#12]
[求API · Issue #178 · cosven/FeelUOwn](https://github.com/cosven/FeelUOwn/issues/178)
[网易云盘相关API · Issue #56 · darknessomi/musicbox](https://github.com/darknessomi/musicbox/issues/56)

这两个 Issue 提到的 API 细节可能有帮助。

**Comment by typcn** [comment]
这些都是 Web 的 API ，不适合。。。。客户端的加密 key 也不一样

要 hook 加密函数，把未加密的数据提取出来搞。。 现在没这个精力啊。。

**Comment by magic-akari** [comment]
总之很感谢作者的付出。
如果继续做的话，付费歌曲可以不做，只做下架歌曲就好。

之前好像有个反代理的被发警告函了[Chion82/163-music-unlock](https://github.com/Chion82/163-music-unlock)，不做付费绕过，会宽容一点吧。
