### ISSUE TITLE
文件替换后原来被下架的歌解锁了但是依然不能播放

### ISSUE THREAD

**Issue by zhangliugang** [typcn/163music-mac-client-unlock#3]

**Comment by typcn** [comment]
海外请使用 unlock_outside

**Comment by zhangliugang** [comment]
不知道为什么,我在国内,但是换了unlock_outs就行了...

**Comment by typcn** [comment]
可能是你的 dns 有问题，解析到了国外

请确认 m1到m3.music.126.net 使用国内 dns 解析（也可以加 hosts），并且没有走代理

**Comment by zhangliugang** [comment]
应该是电信的问题,刚才竟然没开代理登进了FB. 不管怎样非常感谢提供这个工具
