### ISSUE TITLE
网易云音乐1.4.2 (446)版无效

### ISSUE THREAD

**Issue by vivahu** [typcn/163music-mac-client-unlock#4]
OSX版本：10.11.4
网易云音乐版本：Version 1.4.2 (446)

现象为点了图标之后没反应，无报错，但不启动。

已经执行过 chmod +x /Applications/NeteaseMusic.app/Contents/MacOS/NeteaseMusic 加运行权限了

**Comment by typcn** [comment]
控制台启动看日志

**Comment by vivahu** [comment]
怎么看日志？

**Comment by typcn** [comment]
Console.app 里面有，终端执行也可以

**Comment by typcn** [comment]
这个跟版本没任何关系的..只是劫持了网络通讯函数，目测你重命名的不太正确，原来的文件名要改成 NeteaseMusic.org ，注意不要多空格

**Comment by vivahu** [comment]
原理大概到类似Windows的DLL劫持，启动日志如下图所示：

![image](https://cloud.githubusercontent.com/assets/1997175/14037607/07ea24ac-f281-11e5-9d0a-7bfad450d49b.png)

然后弹出了一个「网易云音乐崩溃，Ignore，Report」的弹窗。会是Proxy问题吗？我开着GoAgentX的自动代理模式。

**Comment by vivahu** [comment]
文件肯定没加空格啦。

![image](https://cloud.githubusercontent.com/assets/1997175/14037646/63cbe814-f281-11e5-87e7-25c9a434646e.png)

**Comment by typcn** [comment]
签名验证问题...先到设置-安全，允许任意来源，启动一次，再调回去应该就好了

**Comment by vivahu** [comment]
我一直就是设置的你说的「允许任何来源」，因为有些app用的盗版，必须开这个。
![image](https://cloud.githubusercontent.com/assets/1997175/14037664/91ec6570-f281-11e5-940f-9a5050ad804c.png)

**Comment by jilulu** [comment]
來報一個類似的問題：
海外用戶，下架歌曲無法播放，
Log：
25/3/2016 7:21:13.855 PM NeteaseMusic.org[46299]: Excited! 拼接了 1 个 URL
25/3/2016 7:21:19.196 PM NeteaseMusic.org[46299]: Fid select failed

**Comment by typcn** [comment]
难道你用的是 App Store 版？换官网版试试

**Comment by typcn** [comment]
Fid select failed 是网易的 API 没返回文件 ID 信息。。

**Comment by tasselx** [comment]
@typcn 从歌手页进去好像歌曲没有被替换，热门单曲和查看全部热门单曲没有被替换，然后如果是进入专辑查看全部的话则有替换

**Comment by typcn** [comment]
@typcn 忘记了，晚上加一下

**Comment by vivahu** [comment]
@typcn 之前确实用的App Store版，更换官网版后OK，看来App Store版的验证方式确实不太一样。不过我一般是如果两边版本号一致，肯定会优先用App Store版的。

**Comment by vivahu** [comment]
我的问题解决，如果有其他问题，请另开issue吧，毕竟不是相同的原因。

**Comment by typcn** [comment]
App Store 会对应用进行非常严格的验证，就算资源文件有一丁点损坏也会拒绝启动。。
