### ISSUE TITLE
无法打开

### ISSUE THREAD

**Issue by mxm145** [typcn/163music-mac-client-unlock#5]
按照你的操作之后直接打不开

**Comment by typcn** [comment]
POST LOGS

**Comment by mxm145** [comment]
- http://v1.freep.cn/3tb_160327135007ard5512293.jpg

**Comment by typcn** [comment]
![image](https://cloud.githubusercontent.com/assets/8022103/14064051/a134d10e-f423-11e5-9d81-4bad55f107d8.png)

**Comment by zzBelieve** [comment]
@mxm145    I think you don not put  "NeteaseMusic" to the folder.  Just like this.Thank you very much !@typcn 
![default](https://cloud.githubusercontent.com/assets/10309351/14064229/e702c4c6-f42c-11e5-943e-4c2d96315d48.png)

**Comment by kjlawrencelaw** [comment]
@mxm145 come on, doesnt it put in the package of Mac Client !!!?
it seems that you put it in your iOS app???

**Comment by kjlawrencelaw** [comment]
@zzBelieve thank you, it's work'n for me.

**Comment by mxm145** [comment]
![e75bbdf6-96b3-4e47-b716-ea8330cba291](https://cloud.githubusercontent.com/assets/869702/14064457/537d66fc-f436-11e5-820e-5284d679a13e.png)
肯定是放进去了的啊

**Comment by typcn** [comment]
Please post your logs in "Console.app"

**Comment by mxm145** [comment]
<img width="1021" alt="2016-03-27 6 28 50" src="https://cloud.githubusercontent.com/assets/869702/14064993/0252a7d8-f44a-11e5-8114-ff2479ae23e3.png">

**Comment by mxm145** [comment]
是这样的吗？

**Comment by typcn** [comment]
Search before you ask

https://github.com/typcn/163music-mac-client-unlock/issues/4
