### ISSUE TITLE
替换后出现crash

### ISSUE THREAD

**Issue by tinyboxxx** [typcn/163music-mac-client-unlock#7]
Process:               NeteaseMusic.org [1692]
Path:                  /Applications/NeteaseMusic.app/Contents/MacOS/NeteaseMusic
Identifier:            com.netease.163music
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           NeteaseMusic.org [1692]
User ID:               501

Date/Time:             2016-03-29 12:40:38.607 +0800
OS Version:            Mac OS X 10.11.4 (15E65)
Report Version:        11
Anonymous UUID:        E90070D7-AA60-A111-9863-0565D4917873

Time Awake Since Boot: 870 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (Code Signature Invalid)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

kernel messages:

VM Regions Near 0x105f3c96b (cr2):
--> 
    mapped file            00000001097c6000-0000000109919000 [ 1356K] r-x/rwx SM=COW  ,

Thread 0 Crashed:
0   dyld                            0x00007fff6bda8000 _dyld_start + 0

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x000000000000000d  rbx: 0x0000000000000000  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x0000000000000000  rsi: 0x0000000000000000  rbp: 0x0000000000000000  rsp: 0x00007fff56439c50
   r8: 0x0000000000000000   r9: 0x0000000000000000  r10: 0x0000000000000000  r11: 0x0000000000000000
  r12: 0x0000000000000000  r13: 0x0000000000000000  r14: 0x0000000000000000  r15: 0x0000000000000000
  rip: 0x00007fff6bda8000  rfl: 0x0000000000000201  cr2: 0x0000000105f3c96b

Logical CPU:     0
Error Code:      0x0200003b
Trap Number:     133

Binary Images:
    0x7fff6bda7000 -     0x7fff6bdde0d7  dyld (???) <D9B236BC-4AC1-325F-B3EF-3F06DBDA7119> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 884
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=308K resident=0K(0%) swapped_out_or_unallocated=308K(100%)
Writable regions: Total=10.2M written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=10.2M(100%)

```
                            VIRTUAL   REGION 
```

REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
Process Corpse Info               2048K        2 
STACK GUARD                       56.0M        2 
Stack                             8192K        2 
VM_ALLOCATE                          4K        2 
VM_ALLOCATE (reserved)               4K        2         reserved VM address space (unallocated)
__DATA                             240K        3 
__LINKEDIT                          84K        2 
__TEXT                             224K        2 
mapped file                       1796K        4 
shared memory                        8K        3 
===========                     =======  ======= 
TOTAL                             68.3M       14 
TOTAL, minus reserved VM space    68.3M       14 

Model: iMac14,2, BootROM IM142.0118.B00, 4 processors, Intel Core i7, 3.4 GHz, 16 GB, SMC 1.30f3
Graphics: NVIDIA GeForce GTX 760, NVIDIA GeForce GTX 760, PCIe, 4095 MB
Memory Module: BANK0/DIMM1, 8 GB, DDR3, 1777 MHz, Kingston, KHX1866C10D38G
Memory Module: BANK1/DIMM1, 8 GB, DDR3, 1600 MHz, Kingston, KHX1600C10D38G
Network Service: Ethernet, Ethernet, en0
Serial ATA Device: Samsung SSD 840 EVO 120GB, 120.03 GB
Serial ATA Device: ST3250310AS, 250.06 GB
Serial ATA Device: WDC WD20EARX-00MMMB0, 2 TB
USB Device: USB 3.0 Bus
USB Device: USB Receiver
USB Device: iPhone
USB Device: Composite Device
USB Device: USB 2.0 Bus
USB Device: Hub
USB Device: USB 2.0 Bus
USB Device: Hub
Thunderbolt Bus:

**Comment by typcn** [comment]
https://github.com/typcn/163music-mac-client-unlock/issues/5
https://github.com/typcn/163music-mac-client-unlock/issues/4

Search before you ask

**Comment by tinyboxxx** [comment]
That's work for me! Thanks!
I'm new to Github,and you can add 'Not works with App Store app' in readme!

have a good day,love your work!

**Comment by typcn** [comment]
Added , Thanks
