### ISSUE TITLE
并没有解锁全部音乐？

### ISSUE THREAD

**Issue by elicip** [typcn/163music-mac-client-unlock#8]
比如http://music.163.com/#/m/song?id=27671478 这首，比如swift的歌曲还是不可以下载

**Comment by typcn** [comment]
收费歌曲没有接口来获取的， 获取歌曲信息的接口只能拿到 96Kbps 的低画质文件 ID，除非买一个公共账号劫持请求到服务器上。。

**Comment by elicip** [comment]
是看到你README上写

> Enjoy! All paid and blocked music are unlocked !

**Comment by typcn** [comment]
是的。。。 收费的只能听一般音质。。。不能拿最高音质

**Comment by elicip** [comment]
明白了，主要是解锁了试听
但是有些网易自己灰掉的歌曲现在能下载了，这下载下来的是最高音质还是试听音质？

**Comment by typcn** [comment]
灰掉的默认是 320Kbps ，至于客户端怎么处理这个下载逻辑我也不清楚。。。

**Comment by typcn** [comment]
劫持的 dylib 默认会返回 320Kbps 的 URL （忽略设置）
