### ISSUE TITLE
付费歌曲播放失败

### ISSUE THREAD

**Issue by tasselx** [typcn/163music-mac-client-unlock#9]
尝试播放taylor swift的歌都是播放失败

**Comment by typcn** [comment]
过段时间基于音乐云盘做个新解析，最近略忙...

**Comment by JustZiya** [comment]
网易云音乐发布了 1.4.3.452 ，版本说明是修复了付费用户无法下载 taylor swift 歌曲的问题

**Comment by kjlawrencelaw** [comment]
fail with version 1.4.4…………

**Comment by graywen24** [comment]
1.4.4用的挺好。。。打算短期内部升级了。。。我一看bigbang的歌可以听 就知道没问题了哈哈
